TASK_FORMATION_CHANGE = 1
TASK_INSPECT_QR = 2
TASK_REMOVE_MEMBER = 3
TASK_REJOIN_SWARM = 4
TASK_WAIT = 5

CAP_CAMERA = 1 << 0
CAP_PRECISION_LAND = 1 << 1
CAP_PAYLOAD = 1 << 2
CAP_LONG_RANGE = 1 << 3
CAP_FAILOVER_LEADER = 1 << 4

HEALTH_OK = 0
HEALTH_DEGRADED = 1
HEALTH_CRITICAL = 2

AVAIL_IDLE = 0
AVAIL_EXECUTING = 1
AVAIL_UNAVAILABLE = 2
